blueprints/operate.py
import os
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash, session
from sqlalchemy import or_
from exts import db
from decorators import login_required
from .forms import *
from decorators import login_required
from datetime import datetime
bp = Blueprint("operate", __name__, url_prefix="/operate")
# 定义用一些操作

# 搜索歌曲功能
@bp.route("/search", methods=['GET','POST'])
def search():
    if request.method == 'GET':
        return render_template("search.html")
    else:
        musicname = request.form.get("m")  # 要搜索的歌曲
        if musicname is None:
            flash('请输入歌曲或歌手名称')
            return render_template("search.html")  # 当没有提供歌曲名时给音乐的提示
        song_singers = get_songs(musicname)
        singer = musicname
        singer_songs = get_songs_(singer)
        return render_template("search_result.html",  song_singers=song_singers, singer_songs=singer_songs)  # 把song_singers也传入前端


# 显示所有用户的信息
@bp.route('/user_list',methods=['GET','POST'])
def user_list():
    if request.method == 'GET':
        page = request.args.get("page", type=int, default=1)   # 当没有参数时默认为一,转成整形很重要，默认为string
        # 分页器对象
        paginate = UserModel.query.paginate(page=page, per_page=12)  # 当前页和每页展示多少数据

        return render_template("user-list.html", paginate=paginate,)  # 把paginate对象传到前端
    else:
        user_id = request.form.get("userid")  # 要搜索用户id
        if user_id == '':
            flash("请输入数据")
            return redirect(url_for("operate.user_list"))  # 当没有
        else:
            users = UserModel.query.filter(or_(UserModel.UserID == user_id, UserModel.UserName == user_id))
            if not users:
                flash("不存在此用户")
                redirect(url_for("operate.user_list"))
            else:
                return redirect(url_for("operate.user_search", user_id=user_id))

# 删除指定用户的信息
@bp.route('/user_delete/<string:user_id>')
def user_delete(user_id):
    orders = OrderModel.query.filter_by(UserID=user_id).all()  # 订单
    for order in orders:
        ordering = OrderingModel.query.filter_by(OrderID=order.OrderID).all()  # 先删除下单
        for item in ordering:
            db.session.delete(item)
        db.session.commit()
        db.session.delete(order)   # 再删除订单
        db.session.commit()
    user = UserModel.query.get(user_id)  # 最后删除用户
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("operate.user_list"))

@bp.route('/user_search/<string:user_id>',methods=['GET','POST'])
def user_search(user_id):
    if request.method == 'GET':
        userid = user_id
        username = user_id
        users = UserModel.query.filter(or_(UserModel.UserID.contains(userid), UserModel.UserName.contains(username)))
        return render_template("user-list.html", users=users, paginate=None)
    else:
        user_id = request.form.get("userid")  # 要搜索用户id
        if user_id == '':
            flash("请输入数据")
            return redirect(url_for("operate.user_list"))  # 当没有
        else:
            return redirect(url_for("operate.user_search", user_id=user_id))
# 添加用户
@bp.route('/user_add',methods=['GET','POST'])
def user_add():
    if request.method == 'GET':
        return render_template('user-add.html')
    else:
        form = AddUserForm(request.form)  # 获取前端用户提交的form数据扔给registerform进行验证
        if form.validate():  # 调用验证器和验证函数
            userid = form.UserID.data
            email = form.Email.data
            username = form.UserName.data
            password = form.Password.data
            contactnum = form.ContactNumber.data
            user = UserModel(UserID=userid, Email=email, UserName=username, Password=password, ContactNumber=contactnum)
            db.session.add(user)
            db.session.commit()
            flash("用户添加成功！")  # 添加Flash消息
            return redirect(url_for("operate.user_list"))  # 把视图函数转换成url 蓝图.视图函数
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f'错误：{error} ')
            return redirect(url_for("operate.user_add"))

@bp.route('/user_edit/<string:user_id>',methods=['GET','POST'])
def user_edit(user_id):
    if request.method == 'GET':
        return render_template('user-edit.html')
    else:
        form = EditUserForm(request.form)  # 获取前端用户提交的form数据扔给registerform进行验证
        if form.validate():  # 调用验证器和验证函数
            userid = user_id
            user = UserModel.query.get(userid)
            user.Email = form.Email.data
            user.UserName = form.UserName.data
            db.session.commit()
            flash("用户信息修改成功！")  # 添加Flash消息
            return redirect(url_for("operate.user_list"))  # 把视图函数转换成url 蓝图.视图函数
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f'错误：{error} ')
            print(form.errors)
            return redirect(url_for("operate.user_edit", user_id=user_id))




# 显示所有音乐的信息
@bp.route('/music_list',methods=['GET','POST'])
def music_list():
    if request.method == 'GET':
        page = request.args.get("page", type=int, default=1)   # 当没有参数时默认为一,转成整形很重要，默认为string
        # 分页器对象 
        paginate = db.session.query(MusicModel, SingerModel).\
            join(SingingModel, MusicModel.MusicID == SingingModel.MusicID).\
            join(SingerModel, SingerModel.SingerID == SingingModel.SingerID).paginate(page=page, per_page=12)
        
        return render_template("music-list.html", paginate=paginate)  # 把paginate对象传到前端
    else:
        music_id = request.form.get("musicid")  # 要搜索音乐id
        if music_id == '':
            flash("请输入数据")
            return redirect(url_for("operate.music_list"))  # 当没有
        else:
            musics = MusicModel.query.filter(or_(MusicModel.MusicID == music_id, MusicModel.MusicName == music_id))
            if not musics:
                flash("不存在此音乐")
                redirect(url_for("operate.music_list"))
            else:
                return redirect(url_for("operate.music_search", music_id=music_id))


# 删除指定音乐的信息
@bp.route('/music_delete/<string:music_id>')
def music_delete(music_id):
    drop_music = MusicModel.query.get(music_id)  # 删除音乐的id
    db.session.delete(drop_music)
    db.session.commit()
    return redirect(url_for("operate.music_list"))

# 搜索音乐信息
@bp.route('/music_search/<string:music_id>',methods=['GET','POST'])
def music_search(music_id):
    if request.method == 'GET':
        musicid = music_id
        musicname = music_id
        page = request.args.get("page", type=int, default=1)   # 当没有参数时默认为一,转成整形很重要
        # 分页器对象 
        paginate = db.session.query(MusicModel, SingerModel).\
            join(SingingModel, MusicModel.MusicID == SingingModel.MusicID).\
            join(SingerModel, SingerModel.SingerID == SingingModel.SingerID).\
            filter(or_(MusicModel.MusicID.contains(musicid), MusicModel.MusicName.contains(musicname))).\
            paginate(page=page, per_page=12)
        
        return render_template("music-list.html", paginate=paginate)  # 把paginate对象传到前端
    else:
        music_id = request.form.get("musicid")  # 要搜索音乐id
        if music_id == '':
            flash("请输入数据")
            return redirect(url_for("operate.music_list"))  # 当没有
        else:
            return redirect(url_for("operate.music_search", music_id=music_id))
        
# 添加音乐 
@bp.route('/music_add',methods=['GET','POST'])
def music_add():
    if request.method == 'GET':
        return render_template('music-add.html')
    else:
        form = AddMusicForm(request.form)  # 获取前端音乐提交的form数据扔给registerform进行验证
        if form.validate():  # 调用验证器和验证函数
            musicf = request.files['musicfile']
            coverf = request.files['coverfile']
            musicf.save(os.path.join("static/musics/", musicf.filename))
            coverf.save(os.path.join("static/images/", coverf.filename))

            musicid = form.MusicID.data
            musicname = form.MusicName.data
            intro = form.Intro.data
            classid = form.ClassID.data
            price = form.price.data
            issuetime = form.IssueTime.data
            storagelocation = os.path.join(musicf.filename)
            coverlocation = coverf.filename.split('.')[0]
            
            singerid = form.SingerID.data
            singername = form.Singer.data
            singersex = form.SingerSex.data
            singerflag = SingerModel.query.filter_by(SingerID=singerid).first()  # 返回第一个歌手
            
            music = MusicModel(MusicID=musicid, MusicName=musicname, ClassID=classid, Intro=intro, price=price, IssueTime=issuetime, StorageLocation=storagelocation, Cover=coverlocation)
            if not singerflag:
                singer = SingerModel(SingerID=singerid, Singer=singername, SingerSex=singersex)
                db.session.add(singer)
            singing = SingingModel(SingerID=singerid, MusicID=musicid)
            db.session.add(music)
            db.session.add(singing)
            db.session.commit()
            flash("音乐添加成功！")  # 添加Flash消息
            return redirect(url_for("operate.music_list"))  # 把视图函数转换成url 蓝图.视图函数
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(f'错误：{error} ')
            return redirect(url_for("operate.music_add"))

# 修改音乐信息 
@bp.route('/music_edit/<string:music_id>?<string:singer_id>',methods=['GET','POST'])
def music_edit(music_id, singer_id):
    if request.method == 'GET':
        return render_template('music-edit.html')
    else:
        form = EditMusicForm(request.form)  # 获取前端音乐提交的form数据扔给registerform进行验证
        if form.validate():  # 调用验证器和验证函数
            musicf = request.files['musicfile']

templates/ad_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>广告管理系统 - X-admin</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/font.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/xadmin.css')}}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='lib/layui/layui.js')}}" charset="utf-8"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/xadmin.js')}}"></script>
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div class="x-nav">
        <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
            <i class="layui-icon" style="line-height:30px">ဂ</i>
        </a>
    </div>
    <div class="x-body">
        <div class="layui-row">
           <a class="layui-btn" href="{{url_for('operate.ad_add')}}">添加广告</a>
        </div>
        <xblock>

        </xblock>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        <table class="layui-table">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>ID</th>
                    <th>摘要</th>
                    <th>标题</th>
                    <th>发布时间</th>
                    <th>内容</th>
                    <th>图片</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% if paginate is not none %}
                {% set i = (paginate.page - 1) * paginate.per_page + 1 %}
                {% for ad in paginate.items %}
                <tr>
                    <td>{{ i }}
                    </td>
                    <td>{{ ad.AdvertisingID }}</td>
                    <td>{{ ad.Abstract }}</td>
                    <td>{{ ad.title }}</td>
                    <td>{{ ad.ReleaseTime.strftime('%Y-%m-%d %H:%M:%S') if ad.ReleaseTime else '' }}</td>
                    <td>{{ ad.content }}</td>
                    <td>{{ ad.Picture }}</td>
                    <td class="td-manage">
                        <button title="删除" onclick="ad_del(this,'{{ad.AdvertisingID}}')">删除</button>
                        <i class="layui-icon">&#xe640;</i>
                    </td>
                </tr>
                {% set i = i + 1 %}
                {% endfor %}
                {% else %}
                {% set i = 1 %}
                {% for ad in ads %}
                <tr>
                    <td>{{ i }}
                    </td>
                    <td>{{ ad.AdvertisingID }}</td>
                    <td>{{ ad.Abstract }}</td>
                    <td>{{ ad.title }}</td>
                    <td>{{ ad.ReleaseTime.strftime('%Y-%m-%d %H:%M:%S') if ad.ReleaseTime else '' }}</td>
                    <td>{{ ad.content }}</td>
                    <td>{{ ad.Picture }}</td>
                    <td class="td-manage">
                        <button title="删除" onclick="ad_del(this,'{{ad.AdvertisingID}}')">删除</button>
                        <i class="layui-icon">&#xe640;</i>
                    </td>
                </tr>
                {% set i = i + 1 %}
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <div class="page">
            <div>
                {% if paginate is not none %}
                <!-- 左一页 -->
                {% if not paginate.has_prev %}
                <!-- 没有左页就不显示左标签-->
                <a class="prev" href="{{url_for('operate.ad_list')}}?page={{paginate.prev_num}}">&lt;&lt;</a>
                {% endif %}

                {% for num in range(1,paginate.pages+1) %}
                {% if num == paginate.page %}
                <span class="current" href="{{url_for('operate.ad_list')}}?page={{num}}">{{num}}</span>
                {% endif %}
                {% endfor %}

                <!-- 右一页 -->
                {% if not paginate.has_next %}
                <!-- 没有右页就不显示左标签-->
                <a class="next" href="{{url_for('operate.ad_list')}}?page={{paginate.next_num}}">&gt;&gt;</a>
                {% endif %}
                {% endif %}
            </div>

        </div>

    </div>
    <script>
        layui.use('laydate', function () {
            var laydate = layui.laydate;

            //执行一个laydate实例
            laydate.render({
                elem: '#start' //指定元素
            });

            //执行一个laydate实例
            laydate.render({
                elem: '#end' //指定元素
            });
        });

        /*广告-删除*/
        function ad_del(obj, id, callback) {
            layer.confirm('确认要删除吗？', function (index) {
                //发异步删除数据
                $(obj).parents("tr").remove();
                layer.msg('已删除!', {
                    icon: 1,
                    time: 1000
                });
                window.location.href = "/operate/ad_delete/" + id;
            });
        }
    </script>
    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
</body>

</html>

templates/admin_login.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>后台登录-X-admin2.0</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="../static/css/font.css">
	<link rel="stylesheet" href="../static/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="../static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="../static/js/xadmin.js"></script>

</head>
<body class="login-bg">
    
    <div class="login">
        <div class="message">x-admin2.0-管理登录</div>
        <div id="darkbannerwrap"></div>
        
        <form method="POST" class="layui-form" >
            <input name="AdminId" placeholder="用户名"  type="text" lay-verify="required" class="layui-input" >
            <hr class="hr15">
            <input name="Password" lay-verify="required" placeholder="密码"  type="password" class="layui-input">
            <hr class="hr15">
            <input value="登录" lay-submit lay-filter="login" style="width:100%;" type="submit">
            <hr class="hr20" >
        </form>
    </div>

</body>
</html>

templates/chart-add.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/font.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename='css/xadmin.css')}}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='lib/layui/layui.js')}}" charset="utf-8"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/xadmin.js')}}"></script>

    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-body">
        <form class="layui-form" method="POST" enctype="multipart/form-data">
            <div class="layui-form-item">
              <label for="L_musicid" class="layui-form-label">
                  <span class="x-red">*</span>榜单ID
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_userid" name="ChartID" required=""  class="layui-input">
              </div>
                <div class="layui-form-mid layui-word-aux">
                  1位数字
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_musicname" class="layui-form-label">
                  <span class="x-red">*</span>榜单名
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_musicname" name="ChartType" required=""  class="layui-input">
              </div>
          </div>
            <div class="layui-form-item">
              <label for="L_musicid" class="layui-form-label">
                  <span class="x-red">*</span>音乐ID
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_userid" name="MusicID" required=""  class="layui-input">
              </div>
                <div class="layui-form-mid layui-word-aux">
                  5位数字
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_musicname" class="layui-form-label">
                  <span class="x-red">*</span>音乐名
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_musicname" name="MusicName" required=""  class="layui-input">
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_musicname" class="layui-form-label">
                  <span class="x-red">*</span>排名
              </label>
              <div class="layui-input-inline">
                  <input type="text" id="L_musicname" name="SongRanking" required=""  class="layui-input">
              </div>
              <div class="layui-form-mid layui-word-aux">
                1-10数字
              </div>
          </div>
          <div class="layui-form-item">
              <label for="L_repass" class="layui-form-label">
              </label>
              <button  class="layui-btn" lay-filter="add" lay-submit="">
                  增加
              </button>
          </div>
      </form>
    </div>
            {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class="flashes">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>

templates/music-list.html
<!DOCTYPE html>
<html>
  
  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/font.css')}}">
	<link rel="stylesheet" href="{{url_for('static', filename='css/xadmin.css')}}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="{{url_for('static', filename='lib/layui/layui.js')}}" charset="utf-8"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/xadmin.js')}}"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body>
    <div class="x-nav">
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so" method="Post">
          <input type="text" name="musicid"  placeholder="请输入音乐名或id" autocomplete="off" class="layui-input">
          <button class="layui-btn"  lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
      </div>
      <xblock>
        <a class="layui-btn" href="{{url_for('operate.music_list')}}">返回音乐列表</a>
          <a class="layui-btn" href="{{url_for('operate.music_add')}}">添加</a>
      </xblock>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class="flashes">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
      <table class="layui-table">
        <thead>
          <tr>
            <th>序号
            </th>
            <th>音乐ID</th>
            <th>音乐名</th>
            <th>类别ID</th>
            <th>价格</th>
            <th>发布时间</th>
            <th>操作</th></tr>
        </thead>
        <tbody>
        {% if paginate %}
			 {% for music in paginate.items %}<!-- musics.items返回的是music对象 -->
             <tr>
                 {% set i=loop.index+12*(paginate.page-1) %}
                <td>{{ i }}</td>
                <td>{{music.MusicID}}</td>
                <td>{{music.MusicName}}</td>
                <td>{{music.ClassID}}</td>
                <td>{{music.price}}</td>
                <td>{{music.IssueTime}}</td>
                <td class="td-manage">
                    <a title="编辑"   href="{{url_for('operate.music_edit',music_id=music.MusicID)}}">编辑</a>
                <i class="layui-icon">&#xe642;</i>
                  <button title="删除" onclick="member_del(this,'{{music.MusicID}}')" >删除</button>
                    <i class="layui-icon">&#xe640;</i>

                </td>
              </tr>
			{% endfor %}
        {% else %}
             {% for music in musics %}
                <tr>
                    {% if paginate is not none %}
                    {% set i=loop.index+paginate.per_page*(paginate.page-1) %}
                    <td>{{ i }}</td>
                    {% else %}
                    <td>{{ loop.index }}</td>
                    {%endif%}
                    <td>{{music.MusicID}}</td>
                    <td>{{music.MusicName}}</td>
                    <td>{{music.ClassID}}</td>
                    <td>{{music.price}}</td>
                    <td>{{music.IssueTime}}</td>
                    <td class="td-manage">
                        <a title="编辑"   href="{{url_for('operate.music_edit',music_id=music.MusicID)}}">编辑</a>
                <i class="layui-icon">&#xe642;</i>
                      <button title="删除" onclick="member_del(this,'{{music.MusicID}}')">删除</button>
                        <i class="layui-icon">&#xe640;</i>
                      </a>
                    </td>
                  </tr>
        {% endfor %}
        {% endif %}
        </tbody>
      </table>
      <div class="page">
        <div>
          {% if paginate%}
          <!-- 左一页 -->
          {% if paginate.has_prev %} <!-- 没有左页就不显示左标签-->
          <a class="prev" href="{{url_for('operate.music_list')}}?page={{paginate.prev_num}}">&lt;&lt;</a>
          {% endif %}

          {% for num in range(paginate.page-3,paginate.page+4) %}
            {%if num >=1%}
          {% if num == paginate.page  %}
          <span class="current" href="{{url_for('operate.music_list')}}?page={{num}}">{{num}}</span>
          {% else %}
            <span class="" href="{{url_for('operate.music_list')}}?page={{num}}">{{num}}</span>
            {% endif %}
            {%endif%}
          {% endfor %}

          <!-- 右一页 -->
          {% if paginate.has_next %} <!-- 没有右页就不显示左标签-->
          <a class="next" href="{{url_for('operate.music_list')}}?page={{paginate.next_num}}">&gt;&gt;</a>
          {% endif %}
          {% endif %}
        </div>

      </div>

    </div>
    <script>
      layui.use('laydate', function(){
        var laydate = layui.laydate;
        
        //执行一个laydate实例
        laydate.render({
          elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
          elem: '#end' //指定元素
        });
      });



      /*音乐-删除*/
        function member_del(obj,id, callback){
            layer.confirm('确认要删除吗？',function(index){
                //发异步删除数据
                $(obj).parents("tr").remove();
                layer.msg('已删除!',{icon:1,time:1000});
                window.location.href="/operate/music_delete/" + id;
            });
        }


      function delAll (argument) {

        var data = tableCheck.getData();
  
        layer.confirm('确认要删除吗？'+data,function(index){
            //捉到所有被选中的，发异步进行删除
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
      }
    </script>
    <script>var _hmt = _hmt || []; (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();</script>
  </body>

</html>